/**
 * @fileoverview gRPC-Web generated client stub for chatprotocol
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.3
// source: ChatGPT.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.chatprotocol = require('./ChatGPT_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chatprotocol.ChatProtocolClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chatprotocol.ChatProtocolPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chatprotocol.UserRequest,
 *   !proto.chatprotocol.UserReply>}
 */
const methodDescriptor_ChatProtocol_DiscoverMe = new grpc.web.MethodDescriptor(
  '/chatprotocol.ChatProtocol/DiscoverMe',
  grpc.web.MethodType.UNARY,
  proto.chatprotocol.UserRequest,
  proto.chatprotocol.UserReply,
  /**
   * @param {!proto.chatprotocol.UserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chatprotocol.UserReply.deserializeBinary
);


/**
 * @param {!proto.chatprotocol.UserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chatprotocol.UserReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chatprotocol.UserReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chatprotocol.ChatProtocolClient.prototype.discoverMe =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chatprotocol.ChatProtocol/DiscoverMe',
      request,
      metadata || {},
      methodDescriptor_ChatProtocol_DiscoverMe,
      callback);
};


/**
 * @param {!proto.chatprotocol.UserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chatprotocol.UserReply>}
 *     Promise that resolves to the response
 */
proto.chatprotocol.ChatProtocolPromiseClient.prototype.discoverMe =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chatprotocol.ChatProtocol/DiscoverMe',
      request,
      metadata || {},
      methodDescriptor_ChatProtocol_DiscoverMe);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chatprotocol.UUIDRequest,
 *   !proto.chatprotocol.UUIDReply>}
 */
const methodDescriptor_ChatProtocol_GenerateUUID = new grpc.web.MethodDescriptor(
  '/chatprotocol.ChatProtocol/GenerateUUID',
  grpc.web.MethodType.UNARY,
  proto.chatprotocol.UUIDRequest,
  proto.chatprotocol.UUIDReply,
  /**
   * @param {!proto.chatprotocol.UUIDRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chatprotocol.UUIDReply.deserializeBinary
);


/**
 * @param {!proto.chatprotocol.UUIDRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chatprotocol.UUIDReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chatprotocol.UUIDReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chatprotocol.ChatProtocolClient.prototype.generateUUID =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chatprotocol.ChatProtocol/GenerateUUID',
      request,
      metadata || {},
      methodDescriptor_ChatProtocol_GenerateUUID,
      callback);
};


/**
 * @param {!proto.chatprotocol.UUIDRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chatprotocol.UUIDReply>}
 *     Promise that resolves to the response
 */
proto.chatprotocol.ChatProtocolPromiseClient.prototype.generateUUID =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chatprotocol.ChatProtocol/GenerateUUID',
      request,
      metadata || {},
      methodDescriptor_ChatProtocol_GenerateUUID);
};


module.exports = proto.chatprotocol;

